export const TOKEN_PATH_TO_PYTHON = 'TOKEN_PATH_TO_PYTHON';
export const TOKEN_PATH_TO_MAIN = 'TOKEN_PATH_TO_MAIN';
export const TOKEN_COMMUNICATION_PORT = 'TOKEN_COMMUNICATION_PORT';
export const TOKEN_FRAME_RATE = 'TOKEN_FRAME_RATE';
